---
# IMPORTANT: Change settings here, but DO NOT change the spacing.
# Remove comments and add values where applicable.
# The descriptions below should be self-explanatory

title: "Data Science Project"
#subtitle: "This will appear as Right Header"

documentclass: "elsarticle"

# --------- Thesis title (Optional - set to FALSE by default).
# You can move the details below around as you please.
Thesis_FP: FALSE
# Entry1: "An unbelievable study with a title spanning multiple lines."
# Entry2: "\\textbf{Nico Katzke}" # textbf for bold
# Entry3: "A thesis submitted toward the degree of Doctor of Philosophy"
# Uni_Logo: Tex/Logo.png # Place a logo in the indicated location (from your root, e.g. defaults to ~/Tex/Logo.png) and uncomment this line. Leave uncommented for no image
# Logo_width: 0.3 # If using a logo - use this to set width (size) of image
# Entry4: "Under the supervision of: \\vfill Prof. Joe Smith and Dr. Frank Smith"
# Entry5: "Stellenbosch University"
# Entry6: April 2020
# Entry7:
# Entry8:

# --------- Front Page
# Comment: ----- Follow this pattern for up to 5 authors
AddTitle: TRUE # Use FALSE when submitting to peer reviewed platform. This will remove author names.
Author1: "Jacques Rossouw"
Ref1: "Stellenbosch University, Western Cape, South Africa" # First Author's Affiliation
Email1: "gerardrossouw\\@gmail.com" # First Author's Email address
# 
# Author2: "John Smith"
# Ref2: "Some other Institution, Cape Town, South Africa"
# Email2: "John\\@gmail.com"
# CommonAffiliation_12: TRUE # If Author 1 and 2 have a common affiliation. Works with _13, _23, etc.
# 
# Author3: "John Doe"
# Email3: "Joe\\@gmail.com"

# CorrespAuthor_1: TRUE  # If corresponding author is author 3, e.g., use CorrespAuthor_3: TRUE
# 
# # Comment out below to remove both. JEL Codes only given if keywords also given.
# keywords: "Multivariate GARCH \\sep Kalman Filter \\sep Copula" # Use \\sep to separate
# JELCodes: "L250 \\sep L100"

# ----- Manage headers and footers:
#BottomLFooter: $Title$
#BottomCFooter:
#TopLHeader: \leftmark # Adds section name at topleft. Remove comment to add it.
BottomRFooter: "\\footnotesize Page \\thepage" # Add a '#' before this line to remove footer.
addtoprule: TRUE
addfootrule: TRUE               # Use if footers added. Add '#' to remove line.

# --------- page margins:
margin: 2.3 # Sides
bottom: 2 # bottom
top: 2.5 # Top
HardSet_layout: TRUE # Hard-set the spacing of words in your document. This will stop LaTeX squashing text to fit on pages, e.g.
# This is done by hard-setting the spacing dimensions. Set to FALSE if you want LaTeX to optimize this for your paper.

# --------- Line numbers
linenumbers: FALSE # Used when submitting to journal

# ---------- References settings:
# You can download cls format here: https://www.zotero.org/ - simply search for your institution. You can also edit and save cls formats here: https://editor.citationstyles.org/about/
# Hit download, store it in Tex/ folder, and change reference below - easy.
bibliography: Tex/ref.bib       # Do not edit: Keep this naming convention and location.
csl: Tex/harvard-stellenbosch-university.csl # referencing format used.
# By default, the bibliography only displays the cited references. If you want to change this, you can comment out one of the following:
#nocite: '@*' # Add all items in bibliography, whether cited or not
# nocite: |  # add specific references that aren't cited
#  @grinold2000
#  @Someoneelse2010

# ---------- General:
RemovePreprintSubmittedTo: TRUE  # Removes the 'preprint submitted to...' at bottom of titlepage
#Journal: "Journal of Finance"   # Journal that the paper will be submitting to, if RemovePreprintSubmittedTo is set to TRUE.
toc: TRUE                       # Add a table of contents
numbersections: TRUE             # Should sections (and thus figures and tables) be numbered?
fontsize: 11pt                  # Set fontsize
linestretch: 1.2                # Set distance between lines.
link-citations: TRUE            # This creates dynamic links to the papers in reference list.

### Adding additional latex packages:
# header-includes:
#    - \usepackage{colortbl} # Add additional packages here.

output:
  pdf_document:
    keep_tex: TRUE
    template: Tex/TexDefault.txt
    fig_width: 3.5 # Adjust default figure sizes. This can also be done in the chunks of the text.
    fig_height: 3.5
abstract: |
  Abstract to be written here.
---

<!-- First: Set your default preferences for chunk options: -->

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      message = FALSE, 
                      warning = FALSE, 
                      fig.width = 6, 
                      fig.height = 5, 
                      fig.pos="H", 
                      fig.pos = 'H')

# Install packages
library(pacman)

pacman::p_load(reticulate, tidyverse, dplyr, corrplot)

py_config()
py_list_packages()

```



<!-- Check the current python version running -->

# Plots


```{r}
    
df <- read_csv("./data/absa_jup.csv", show_col_types = F)
l_names <- c("L_DEPOSITS_DENOMINATED_IN_RAND_TOTAL" = "Deposits Rand",
             "L_DEPOSITS_DENOMINATED_IN_FOREIGN_CURRENCY_TOTAL" = "Deposits Foreign",
             "L_OTHER_BORROWED_FUNDS_TOTAL" = "Other Borrowed Funds",
             "L_FOREIGN_CURRENCY_FUNDING_TOTAL" = "Foreign Funding",
             "L_OTHER_LIABILITIES_TO_THE_PUBLIC_TOTAL" = "Other to Public",
             "L_OTHER_LIABILITIES_TOTAL"  = "Other")

p1 <- df %>%
    select(Date, starts_with("L_")) %>% 
    gather(Liability, Value, 2:7) %>%
    ggplot() +
    geom_line(aes(x = Date, y = cumsum(Value)/1000000,
                  color = Liability), size=0.8) +
    facet_wrap(~Liability, scales = "free_y", ncol=2, 
               labeller = as_labeller(l_names)) +
    # scale_color_hue(labels = element_blank()) +
    # scale_linetype_discrete(labels = element_blank()) +
    guides(col = 'none', linetype = "none") +
    scale_y_continuous(name = "Liability Value (Billions)") +
    labs(title = "Monthly Liability Items in the Absa Ltd Balance Sheet")

p1

 
```

```{r}
df <- read_csv("./data/absa_jup.csv", show_col_types = F)
l_names <- c("A_CENTRAL_BANK_MONEY_AND_GOLD_TOTAL_ASSETS" = "CB Money & Gold",
                "A_DEPOSITS_LOANS_AND_ADVANCES_TOTAL_ASSETS" = 
                "Deposits, Loans, and Advances",
                "A_INVESTMENTS_AND_BILLS_including_trading_portfolio_assets_TOTAL_ASSETS" = 
    "Investments & Bills",
                "A_NON-FINANCIAL_ASSETS_TOTAL_ASSETS" = 
        "Non-Financial Assets",
                "A_OTHER_ASSETS_TOTAL_ASSETS" = "Other Assets",
                "E_TOTAL_EQUITY_TOTAL" = "Total Equity")

p1 <- df %>%
    select(Date, starts_with("A_"), starts_with("E_")) %>% 
    gather(Asset, Value, -1) %>%
    ggplot() +
    geom_line(aes(x = Date, y = cumsum(Value)/1000000,
                  color = Asset), size=0.8) +
    facet_wrap(~Asset, scales = "free_y", ncol=2, 
               labeller = as_labeller(l_names)) +
    # scale_color_hue(labels = element_blank()) +
    # scale_linetype_discrete(labels = element_blank()) +
    guides(col = 'none', linetype = "none") +
    scale_y_continuous(name = "Asset Value (Billions)") +
    scale_x_date("Date (Monthly)") +
    labs(title = "Absa Group Ltd Assets")

p1
# ggsave("./figures/missing_totals.png")

```


```{r}
df <- read_csv("./data/banks_data.csv", show_col_types = F)
l_names <- c("L_DEPOSITS_DENOMINATED_IN_RAND_TOTAL" = "Deposits Rand",
             "L_DEPOSITS_DENOMINATED_IN_FOREIGN_CURRENCY_TOTAL" = "Deposits Foreign",
             "L_OTHER_BORROWED_FUNDS_TOTAL" = "Other Borrowed Funds",
             "L_FOREIGN_CURRENCY_FUNDING_TOTAL" = "Foreign Funding",
             "L_OTHER_LIABILITIES_TO_THE_PUBLIC_TOTAL" = "Other to Public",
             "L_OTHER_LIABILITIES_TOTAL"  = "Other")

p1 <- df %>%
    select(Date, starts_with("L_")) %>% 
    gather(Liability, Value, 2:7) %>%
    ggplot() +
    geom_line(aes(x = Date, y = cumsum(Value)/1000000,
                  color = Liability), size=0.8) +
    facet_wrap(~Liability, scales = "free_y", ncol=2, 
               labeller = as_labeller(l_names)) +
    # scale_color_hue(labels = element_blank()) +
    # scale_linetype_discrete(labels = element_blank()) +
    guides(col = 'none', linetype = "none") +
    scale_y_continuous(name = "Liability Value (Billions)") +
    scale_x_date("Date (Monthly)")+
    labs(title = "Top 6 Banks' Liabilities",
         subtitle = "(Summed ver each banks)")

p1
```

```{r}
df <- read_csv("./data/banks_data.csv", show_col_types = F)
l_names <- c("A_CENTRAL_BANK_MONEY_AND_GOLD_TOTAL_ASSETS" = "CB Money & Gold",
                "A_DEPOSITS_LOANS_AND_ADVANCES_TOTAL_ASSETS" = 
                "Deposits, Loans, and Advances",
                "A_INVESTMENTS_AND_BILLS_including_trading_portfolio_assets_TOTAL_ASSETS" = 
    "Investments & Bills",
                "A_NON-FINANCIAL_ASSETS_TOTAL_ASSETS" = 
        "Non-Financial Assets",
                "A_OTHER_ASSETS_TOTAL_ASSETS" = "Other Assets",
                "E_TOTAL_EQUITY_TOTAL" = "Total Equity")

p1 <- df %>%
    select(Date, starts_with("A_"), starts_with("E_")) %>% 
    gather(Asset, Value, -1) %>%
    ggplot() +
    geom_line(aes(x = Date, y = cumsum(Value)/1000000,
                  color = Asset), size=0.8) +
    facet_wrap(~Asset, scales = "free_y", ncol=2, 
               labeller = as_labeller(l_names)) +
    # scale_color_hue(labels = element_blank()) +
    # scale_linetype_discrete(labels = element_blank()) +
    guides(col = 'none', linetype = "none") +
    scale_y_continuous(name = "Asset Value (Billions)") +
    scale_x_date("Date (Months)") +
    labs(title = "Top Six Banks' Assets & Equity")

p1
```

Next, the differenced values for these variables are plotted.

```{r}
df <- read_csv("./data/banks_data.csv", show_col_types = F)
l_names <- c("L_DEPOSITS_DENOMINATED_IN_RAND_TOTAL" = "Deposits Rand",
             "L_DEPOSITS_DENOMINATED_IN_FOREIGN_CURRENCY_TOTAL" = "Deposits Foreign",
             "L_OTHER_BORROWED_FUNDS_TOTAL" = "Other Borrowed Funds",
             "L_FOREIGN_CURRENCY_FUNDING_TOTAL" = "Foreign Funding",
             "L_OTHER_LIABILITIES_TO_THE_PUBLIC_TOTAL" = "Other to Public",
             "L_OTHER_LIABILITIES_TOTAL"  = "Other")

p1 <- df %>%
    select(Date, starts_with("L_")) %>% 
    gather(Liability, Value, 2:7) %>%
    ggplot() +
    geom_line(aes(x = Date, y = Value/1000000,
                  color = Liability), size=0.8) +
    facet_wrap(~Liability, scales = "free_y", ncol=2, 
               labeller = as_labeller(l_names)) +
    # scale_color_hue(labels = element_blank()) +
    # scale_linetype_discrete(labels = element_blank()) +
    guides(col = 'none', linetype = "none") +
    scale_x_date("Date (Months)") +
    scale_y_continuous(name = "Change in Liabilities (Billions)") +
    labs(title = 
         "Change in Liabilities for the Top Six Banks' Balance Sheet")  
    

p1
```

```{r}
df <- read_csv("./data/banks_data.csv", show_col_types = F)
l_names <- c("A_CENTRAL_BANK_MONEY_AND_GOLD_TOTAL_ASSETS" = "CB Money & Gold",
                "A_DEPOSITS_LOANS_AND_ADVANCES_TOTAL_ASSETS" = 
                "Deposits, Loans, and Advances",
                "A_INVESTMENTS_AND_BILLS_including_trading_portfolio_assets_TOTAL_ASSETS" = 
    "Investments & Bills",
                "A_NON-FINANCIAL_ASSETS_TOTAL_ASSETS" = 
        "Non-Financial Assets",
                "A_OTHER_ASSETS_TOTAL_ASSETS" = "Other Assets",
                "E_TOTAL_EQUITY_TOTAL" = "Total Equity")

p1 <- df %>%
    select(Date, starts_with("A_"), starts_with("E_")) %>% 
    gather(Asset, Value, -1) %>%
    ggplot() +
    geom_line(aes(x = Date, y = Value/1000000,
                  color = Asset), size=0.8) +
    facet_wrap(~Asset, scales = "free_y", ncol=2, 
               labeller = as_labeller(l_names)) +
    # scale_color_hue(labels = element_blank()) +
    # scale_linetype_discrete(labels = element_blank()) +
    guides(col = 'none', linetype = "none") +
    scale_x_date("Date (Months)") +
    scale_y_continuous(name = "Asset Value (Billions)") +
    labs(title = "Change in Assets & Equity for the Top Six Banks")

p1
```

# Feature Importance

```{r eval=FALSE, include=FALSE}
df <- read_csv("./data/feature_imp_select.csv", show_col_types = F)
#df

df %>% 
    mutate(Feature = factor(Feature, 
                               levels = Feature[order(Importance)])) %>%
    ggplot() +
    geom_col(aes(x = Feature, y = Importance), fill = "steelblue") +
    scale_x_discrete(breaks=c("L_OTHER_LIABILITIES_TOTAL",
            "A_CENTRAL_BANK_MONEY_AND_GOLD_TOTAL_ASSETS",
            "E_TOTAL_EQUITY_TOTAL",
            "A_DEPOSITS_LOANS_AND_ADVANCES_TOTAL_ASSETS",
            "A_INVESTMENTS_AND_BILLS_including_trading_portfolio_assets_TOTAL_ASSETS",
            "L_FOREIGN_CURRENCY_FUNDING_TOTAL",
            "A_NON-FINANCIAL_ASSETS_TOTAL_ASSETS",
            "A_OTHER_ASSETS_TOTAL_ASSETS",
            "L_OTHER_LIABILITIES_TO_THE_PUBLIC_TOTAL",
            "L_DEPOSITS_DENOMINATED_IN_FOREIGN_CURRENCY_TOTAL",
            "L_DEPOSITS_DENOMINATED_IN_RAND_TOTAL",
            "L_OTHER_BORROWED_FUNDS_TOTAL"),
        labels=c("Other\nLiabilities", "CB\nMoney\n& Gold", "Equity", 
                 "Deposits\nLoans\nAdvances", "Investments\n&\nBills", 
                 "Foreign\nFunding", "Non-\nFinancial\nAssets", "Other\nAssets", 
                 "Public\nLibilities", "Foreign\nDeposits", "Rand\nDeposits",
                 "Other\nBorrowed\nFunds")) +
    theme(axis.text.x = element_text(color="steelblue", 
                           size=8)) +
    labs(title = "Feature Importance Bar Plot",
         subtitle = "Negative: Exclution yields better model performance\nPositive: Feature should be included")

#ggsave("./figures/Feature_imp_plot.png")

```

```{r}
# cor_plot1 <- function(df){
# 
#     plot1 <- df %>% 
#         cor(.) %>%
#         corrplot(., method = "color", order = "hclust", tl.srt=0, diag = F,
#                  tl.col = "black", addCoef.col = "black",
#                  tl.pos = "l",
#                  tl.cex = 0.8,
#                  number.font = 8)
# 
#     return(plot2)
# }
# 
# cor_plot1(df)
```

\ref{SARB}

<div id="refs"></div>
